import { BloomWindow } from "./bloomTypes";

export const todayBloomWindows: BloomWindow[] = [
  {
    id: "00-02",
    startHour: 0,
    endHour: 2,
    label: "12 AM",
    value: 0.28,
    confidence: 0.75,
    variability: 0.18,
    intensity: 0.28,
    state: "calm",
    pigmentKey: "sleepDebt",
    glucoseAvg: 96,
  },
  {
    id: "02-04",
    startHour: 2,
    endHour: 4,
    label: "2 AM",
    value: 0.24,
    confidence: 0.72,
    variability: 0.16,
    intensity: 0.24,
    state: "calm",
    pigmentKey: "sleepDebt",
    glucoseAvg: 94,
  },
  {
    id: "04-06",
    startHour: 4,
    endHour: 6,
    label: "4 AM",
    value: 0.32,
    confidence: 0.7,
    variability: 0.2,
    intensity: 0.3,
    state: "calm",
    pigmentKey: "recovery",
    glucoseAvg: 101,
  },
  {
    id: "06-08",
    startHour: 6,
    endHour: 8,
    label: "6 AM",
    value: 0.42,
    confidence: 0.84,
    variability: 0.24,
    intensity: 0.38,
    state: "balanced",
    pigmentKey: "settling",
    glucoseAvg: 108,
  },
  {
    id: "08-10",
    startHour: 8,
    endHour: 10,
    label: "8 AM",
    value: 0.48,
    confidence: 0.86,
    variability: 0.22,
    intensity: 0.42,
    state: "balanced",
    pigmentKey: "proteinSteady",
    glucoseAvg: 112,
  },
  {
    id: "10-12",
    startHour: 10,
    endHour: 12,
    label: "10 AM",
    value: 0.54,
    confidence: 0.82,
    variability: 0.28,
    intensity: 0.46,
    state: "balanced",
    pigmentKey: "slowCarb",
    glucoseAvg: 118,
  },
  {
    id: "12-14",
    startHour: 12,
    endHour: 14,
    label: "12 PM",
    value: 0.78,
    confidence: 0.92,
    variability: 0.72,
    intensity: 0.9,
    state: "reactive",
    pigmentKey: "slowCarb",
    glucoseAvg: 128,
    glucosePeak: 136,
    rateOfChange: "+18 mg/dL/hr",
    dataCompleteness: 0.94,
    eventContext: "Lunch logged around 12:35 PM",
    classificationReason: "Your body rose after lunch, then began settling before 2 PM.",
    note: "Post-lunch rise around 1 PM",
  },
  {
    id: "14-16",
    startHour: 14,
    endHour: 16,
    label: "2 PM",
    value: 0.64,
    confidence: 0.82,
    variability: 0.5,
    intensity: 0.64,
    state: "reactive",
    pigmentKey: "fatDelay",
    glucoseAvg: 122,
    classificationReason: "Your body was still a little more reactive here, but beginning to settle.",
    note: "Beginning to settle",
  },
  {
    id: "16-18",
    startHour: 16,
    endHour: 18,
    label: "4 PM",
    value: 0.5,
    confidence: 0.78,
    variability: 0.3,
    intensity: 0.44,
    state: "balanced",
    pigmentKey: "settling",
    glucoseAvg: 112,
  },
  {
    id: "18-20",
    startHour: 18,
    endHour: 20,
    label: "6 PM",
    value: 0.46,
    confidence: 0.75,
    variability: 0.26,
    intensity: 0.4,
    state: "balanced",
    pigmentKey: "movement",
    glucoseAvg: 109,
  },
  {
    id: "20-22",
    startHour: 20,
    endHour: 22,
    label: "8 PM",
    value: 0.38,
    confidence: 0.72,
    variability: 0.22,
    intensity: 0.34,
    state: "calm",
    pigmentKey: "recovery",
    glucoseAvg: 103,
  },
  {
    id: "22-24",
    startHour: 22,
    endHour: 24,
    label: "10 PM",
    value: 0.3,
    confidence: 0.72,
    variability: 0.18,
    intensity: 0.28,
    state: "calm",
    pigmentKey: "baseline",
    glucoseAvg: 98,
  },
];
